lectern/urls.py
from django.conf.urls import patterns, url
from views import ArticleListView, ArticleRawView, ArticleDetailView, ArticleCreate, ArticleUpdate

from lectern import rest_views

urlpatterns = patterns('',
    url(r'^$', ArticleListView.as_view(), name="index"),
    url(r'^(?P<slug>[a-z0-9_-]+)/$', ArticleListView.as_view(), name="category"),
    url(r'^\+add$', ArticleCreate.as_view(), name="add"),
    url(r'^(?P<category>[a-z0-0_-]+)/(?P<slug>[a-z0-9_-]+)/$', ArticleDetailView.as_view(), name="detail"),
    url(r'^(?P<category>[a-z0-9_-]+)/(?P<slug>[a-z0-9_-]+)/\+edit$', ArticleUpdate.as_view(), name="edit"),
    url(r'^(?P<category>[a-z0-9_-]+)/(?P<slug>[a-z0-9_-]+)/\+raw$', ArticleRawView.as_view(), name="raw"),
)

unitycoders/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView

from rest_framework import routers

from lectern.rest_views import ArticleViewSet

router = routers.DefaultRouter()
router.register(r'articles', ArticleViewSet)

urlpatterns = patterns('',
    # Examples:
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', TemplateView.as_view(template_name="unitycoders/index.html"), name='home'),
    url(r'^articles/', include('lectern.urls', namespace='articles', app_name="lectern")),
    url(r'^accounts/', include('gatekeeper.urls', namespace='accounts', app_name='gatekeeper')),
    url(r'^admin/', include(admin.site.urls)),

    # REST API stuff
    url(r'^api/', include(router.urls, namespace='api')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
)

lectern/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=80)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey('Category')
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    abstract = models.TextField(blank=True, null=True)
    body = models.TextField()

    def get_absolute_url(self):
            from django.core.urlresolvers import reverse
            return reverse('lectern:detail', kwargs={'slug':self.slug, 'category':self.category.slug})

    def __unicode__(self):
        return self.title

class RelatedLink(models.Model):
    title = models.CharField(max_length=80)
    url = models.URLField()
    article = models.ForeignKey(Article)

class Category(models.Model):
    title = models.CharField(max_length=25)
    slug = models.SlugField(max_length=25, unique=True)
    abstract = models.TextField(blank=True, null=True)

    def get_absolute_url(self):
            from django.core.urlresolvers import reverse
            return reverse('lectern:category', kwargs={'slug':self.slug})

    def __unicode__(self):
        return self.title

lectern/forms.py
from django import forms
from lectern.models import Article

from crispy_forms.helper import FormHelper
from crispy_forms.layout import *
from crispy_forms.bootstrap import *

class ArticleForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ArticleForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
                TabHolder(
                    Tab('article', InlineField('title'), InlineField('body'), Div(Div(Field('category'),css_class='col-xs-6'), css_class='row')),
                    Tab('metadata', Fieldset('Advanced', PrependedText('slug', 'http://unitycoders.co.uk/articles/mycategory/'), css_id='advanced', css_class='collapse'), 'abstract'),
                ),
                ButtonHolder(Submit('submit', 'Submit'))
        )
        self.helper.html5_required = True

    class Meta:
        model = Article
	fields = ('title', 'body', 'category', 'slug', 'abstract')
        widgets = {
                'abstract': forms.Textarea(attrs={'rows':4}),
        }

lectern/views.py
from django.views.generic.edit import CreateView, UpdateView
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView

from braces import views

from models import Article, Category
from forms import ArticleForm

class ArticleListView(ListView):
    model = Article

    def get_context_data(self, **kwargs):
        context = super(ArticleListView, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
	if 'slug' in self.kwargs:
		context['selected'] = get_object_or_404(Category, slug=self.kwargs['slug'])
        return context

class ArticleDetailView(DetailView):
    model = Article

class ArticleRawView(ArticleDetailView):
    """Like article detail view, only display raw markdown"""
    template_name = "lectern/article_raw.html"

    def render_to_response(self, context, **response_kwargs):
        response = super(ArticleRawView, self).render_to_response(context, **response_kwargs)
        response['content-type'] = 'text/plain'
        return response

class ArticleCreate(views.LoginRequiredMixin,
		    views.PermissionRequiredMixin,
		    CreateView):
    model = Article
    form_class = ArticleForm
    permission_required = "lectern.add_article"

class ArticleUpdate(views.LoginRequiredMixin,
		    views.PermissionRequiredMixin,
		    UpdateView):
    model = Article
    form_class = ArticleForm
    permission_required = "lectern.change_article"

# REST api views
from rest_framework import viewsets
from lectern.serializers import ArticleSerializer
class ArticleViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows articles to be viewed or edited.
    """
    queryset = Article.objects.all()
    serializer_class = ArticleSerializer

lectern/templates/lectern/article_detail.html
{% extends "base_multicol.html" %}

{% load i18n %}
{% load markdown_deux_tags %}

{% block title %}{{object.title}}{% endblock title %}

{% block extra_js %}
<script src='https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML'></script>
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}
});
</script>
{% endblock %}

{% block content %}
<article>
  <header class="page-header">
    <h1>{{object.title}}</h1>
    <p class="byline">Written on {{object.created}} in <a href="{{object.category.get_absolute_url}}">{{object.category}}</a> {% if object.modified %}(last modified {{object.modified}}){% endif %}</p>
  </header>

{% if object.abstract %}
<!-- begin abstract -->
<section class="abstract">
  <h2>{% trans "abstract" %}</h2>
  {{object.abstract}}
</section>
<!-- end abstract -->
{% endif %}

<section>
{{object.body|markdown}}
</section>

<footer>
  {% include "parts/author_bio.html" with author=user %}
  <hr />
  <small>
    This article is released under the <a href="#">Creative Commons attribution share-alike 3.0 licence</a>.
  </small>
</footer>

{% if object.relatedlink_set.all %}
<h2>{% trans "related links" %}</h2>
<ul>
 {% for related in object.relatedlink_set.all %}
   <li><a href="{{related.url}}">{{related.title}}</a></li>
 {% endfor %}
</ul>
</article>
{% endif %}
{% endblock %}

{% block rightbar %}
<div class="panel-body">
  <ul class="nav nav-pills nav-stacked">
    {% if perms.lectern.article_edit %}<li><a href="{% url 'lectern:edit' category=object.category.slug slug=object.slug %}"><i class="fa fa-pencil"></i> Edit</a></li>{% endif %}
    <li><a href="{% url 'lectern:raw' category=object.category.slug slug=object.slug %}"><i class="fa fa-code"></i> View source</a></li>
  </ul>
</div>
{% endblock %}

lectern/templates/lectern/article_form.html
{% extends "base_centered.html" %}

{% load i18n %}
{% load bootstrap3 %}
{% load markdown_deux_tags %}
{% load crispy_forms_tags %}

{% block title %}{% if object %}{% blocktrans %}Editing {{ object }}{% endblocktrans %}{% else %}{% trans "Write new article" %}{% endif %}{% endblock title %}

{% block page-scripts %}
<script src="{{STATIC_URL}}/js/slugify/jquery.slugify.js" type="text/javascript"></script>
<script src="{{STATIC_URL}}/markdown/js/bootstrap-markdown.js"></script>
<link rel="stylesheet" href="{{STATIC_URL}}/markdown/css/bootstrap-markdown.min.css" type="text/css"></link>

<script type"text/javascript">
function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie != '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

function doPreview(e){
	var previewUrl = "/api/articles/preview/";
	var retVal = "";
	var csrftoken = getCookie('csrftoken');
	var params = {'body': e.getContent(), 'csrfmiddlewaretoken':csrftoken}

	jQuery.ajax({
		url: previewUrl,
		data: params,
		success: function(html) {
			retVal = html;
		},
		method: 'POST',
    		async:false
  	});

	return retVal.markdown;
}

$(document).ready(function(){
	$('#id_slug').slugify('#id_title');
	$('#id_body').markdown({
		iconlibrary: 'fa',
		onPreview: doPreview
	});
});
</script>
{% endblock %}

{% block content %}
    {% crispy form %}
{% endblock %}

lectern/templates/lectern/article_list.html
{% extends "base_multicol.html" %}
{% load i18n %}
{% load bootstrap3 %}

{% block title %}{{ selected.title|default:"All articles" }}{% endblock %}

{% block leftbar %}
<h2 class="sr-only">Categories</h2>
<div class="list-group">
    <a class="list-group-item {% if not selected %}active{% endif %}" href="{% url "lectern:index" %}">All articles</a>
    {% for category in categories %}
    <a class="list-group-item {% if selected.slug == category.slug %}active{% endif %}"  href="{% url "lectern:category" category.slug %}">{{category}}</a>
    {% endfor %}
</div>
{% endblock %}

{% block rightbar %}
<h2 class="sr-only">Actions</h2>
<ul class="nav nav-pills nav-stacked">
    {% if perms.lectern.article_add %}
    <li><a href="{% url "lectern:add" %}"><i class="fa fa-plus" aria-hidden="true"></i> Write an article</a></li>
    {% endif %}
</ul>
{% endblock %}

{% block content %}
<h1 class="sr-only">{% trans "our articles" %}</h1>
{% if selected %}
<div class="page-header">
  <h1>{{selected}}</h1>
  {% if selected.abstract %}<p class="lead">{{selected.abstract}}</p>{% endif %}
</div>
{% endif %}

{% for article in object_list %}
  <article>
    <h1><a href="{{article.get_absolute_url}}">{{article}}</a></h1>
    <p><i class="fa fa-calendar"></i> {{article.created}}</p>
    <p>{{article.abstract}}</p>
    <hr />
  </article>
{% endfor %}
{% endblock content %}

lectern/templates/lectern/article_raw.html
---
title: {{object.title}}
slug: {{object.slug}}
category: {{object.category.slug}}
```
{% if object.abstract %}{{object.abstract|safe}}
{% endif %}
{{object.body|safe}}